# Create Beyond Dimensions Fix
# 修复多个仓储链接站指向同一维度网络的不同通道方块时，仓储发报机重复计数的问题

modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory

license="MIT"

[[mods]] #mandatory
modId="cbd_fix" #mandatory
version="1.0.0" #mandatory
displayName="Create-Beyond Stock Fix" #mandatory
authors="MrMoon"
description='''Fixes Create stock ticker / stock link double-counting when multiple packagers target different Beyond Dimensions net pathway blocks of the same dimension net.'''

[[dependencies.cbd_fix]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cbd_fix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.cbd_fix]]
    modId="create"
    mandatory=true
    versionRange="[6.0,6.1)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cbd_fix]]
    modId="beyonddimensions"
    mandatory=true
    versionRange="[0.7,0.8)"
    ordering="AFTER"
    side="BOTH"
